CREATE TABLE "player_attributes" (
	"player_id" integer PRIMARY KEY NOT NULL,
	"corners" smallint NOT NULL,
	"crossing" smallint NOT NULL,
	"dribbling" smallint NOT NULL,
	"finishing" smallint NOT NULL,
	"first_touch" smallint NOT NULL,
	"free_kick_taking" smallint NOT NULL,
	"heading" smallint NOT NULL,
	"long_shots" smallint NOT NULL,
	"long_throws" smallint NOT NULL,
	"marking" smallint NOT NULL,
	"passing" smallint NOT NULL,
	"penalty_taking" smallint NOT NULL,
	"tackling" smallint NOT NULL,
	"technique" smallint NOT NULL,
	"aggression" smallint NOT NULL,
	"anticipation" smallint NOT NULL,
	"bravery" smallint NOT NULL,
	"composure" smallint NOT NULL,
	"concentration" smallint NOT NULL,
	"decisions" smallint NOT NULL,
	"determination" smallint NOT NULL,
	"flair" smallint NOT NULL,
	"leadership" smallint NOT NULL,
	"off_the_ball" smallint NOT NULL,
	"positioning" smallint NOT NULL,
	"teamwork" smallint NOT NULL,
	"vision" smallint NOT NULL,
	"work_rate" smallint NOT NULL,
	"acceleration" smallint NOT NULL,
	"agility" smallint NOT NULL,
	"balance" smallint NOT NULL,
	"jumping_reach" smallint NOT NULL,
	"natural_fitness" smallint NOT NULL,
	"pace" smallint NOT NULL,
	"stamina" smallint NOT NULL,
	"strength" smallint NOT NULL,
	"aerial_reach" smallint NOT NULL,
	"command_of_area" smallint NOT NULL,
	"communication" smallint NOT NULL,
	"eccentricity" smallint NOT NULL,
	"handling" smallint NOT NULL,
	"kicking" smallint NOT NULL,
	"one_on_ones" smallint NOT NULL,
	"reflexes" smallint NOT NULL,
	"rushing_out" smallint NOT NULL,
	"tendency_to_punch" smallint NOT NULL,
	"throwing" smallint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "player_hidden_attributes" (
	"player_id" integer PRIMARY KEY NOT NULL,
	"consistency" smallint NOT NULL,
	"important_matches" smallint NOT NULL,
	"injury_proneness" smallint NOT NULL,
	"dirtiness" smallint NOT NULL,
	"pressure" smallint NOT NULL,
	"professionalism" smallint NOT NULL,
	"ambition" smallint NOT NULL,
	"loyalty" smallint NOT NULL,
	"adaptability" smallint NOT NULL,
	"temperament" smallint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "player_attributes" ADD CONSTRAINT "player_attributes_player_id_players_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_hidden_attributes" ADD CONSTRAINT "player_hidden_attributes_player_id_players_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "players" ADD CONSTRAINT "players_ca_le_pa_check" CHECK ("players"."current_ability" <= "players"."potential_ability");--> statement-breakpoint
ALTER TABLE "players" ADD CONSTRAINT "players_pa_range_check" CHECK ("players"."pa_range_min" <= "players"."pa_range_max");